import { ThemeDefinition, ThemeId } from './types';

export const THEMES: Record<ThemeId, ThemeDefinition> = {
  'cyber-obsidian': {
    id: 'cyber-obsidian',
    name: 'Cyber Obsidian (Terminal / CTF Matrix)',
    tagline: 'Tactical Phosphor & Terminal HUD',
    description: 'High-contrast midnight obsidian background with military terminal scanlines, phosphor emerald telemetry, and amber countdown clocks. Styled for hardcore cybersecurity competitions.',
    vibe: 'Raw, Technical, Hacker-Native, Tactical',
    bestFor: 'Technical college symposiums, CTF teams, late-night code sprints',
    bgClass: 'bg-[#090a0f]',
    cardBg: 'bg-zinc-900/60',
    borderClass: 'border-zinc-800/80',
    textPrimary: 'text-white',
    textSecondary: 'text-zinc-300',
    textMuted: 'text-zinc-500',
    accentClass: 'text-emerald-400',
    accentBadge: 'bg-emerald-950/70 text-emerald-400 border-emerald-800/60',
    fontDisplay: 'font-mono',
    swatches: [
      { label: 'Obsidian Void', hex: '#090a0f', role: 'Main Background' },
      { label: 'Phosphor Green', hex: '#10b981', role: 'Solves & Flags' },
      { label: 'Warning Amber', hex: '#f59e0b', role: 'Match Clock & Leaderboard' },
      { label: 'Zinc Border', hex: '#27272a', role: 'Container Borders' },
    ],
  },
  'titanium-industrial': {
    id: 'titanium-industrial',
    name: 'Titanium Industrial (Clean Enterprise)',
    tagline: 'Precision Engineering & Swiss Layout',
    description: 'Deep titanium slate canvas with razor-sharp slate borders, electric cobalt accents, and stark high-contrast typography. Zero fluff, mathematically aligned margins, and maximum readability.',
    vibe: 'Engineered, Modern Enterprise, Razor Sharp',
    bestFor: 'Formal engineering symposiums, corporate sponsors, faculty judges',
    bgClass: 'bg-[#0b0f19]',
    cardBg: 'bg-[#111827]/80',
    borderClass: 'border-slate-800',
    textPrimary: 'text-slate-100',
    textSecondary: 'text-slate-300',
    textMuted: 'text-slate-500',
    accentClass: 'text-blue-400',
    accentBadge: 'bg-blue-950/70 text-blue-400 border-blue-800/60',
    fontDisplay: 'font-sans font-bold',
    swatches: [
      { label: 'Titanium Slate', hex: '#0b0f19', role: 'Background Canvas' },
      { label: 'Electric Cobalt', hex: '#3b82f6', role: 'Primary Focus & Controls' },
      { label: 'Signal Cyan', hex: '#06b6d4', role: 'System Metrics' },
      { label: 'Steel Border', hex: '#334155', role: 'Structural Dividers' },
    ],
  },
  'midnight-arena': {
    id: 'midnight-arena',
    name: 'Midnight Neon Arena (Esports Stage)',
    tagline: 'High-Energy Auditorium Projector Aesthetic',
    description: 'Deep cosmic void with electric neon cyan, violet-indigo glows, and ultra-bold scoreboard hierarchy. Crafted specifically to pop on big 4K auditorium projectors and live audience streams.',
    vibe: 'Cinematic, Competitive, High-Energy, Electric',
    bestFor: 'Symposium auditorium main stage, big TV projectors, live finals ceremony',
    bgClass: 'bg-[#0a0714]',
    cardBg: 'bg-[#120e24]/70',
    borderClass: 'border-purple-900/50',
    textPrimary: 'text-purple-50',
    textSecondary: 'text-purple-200/80',
    textMuted: 'text-purple-400/60',
    accentClass: 'text-cyan-400',
    accentBadge: 'bg-purple-950/80 text-cyan-300 border-purple-700/60',
    fontDisplay: 'font-mono font-black',
    swatches: [
      { label: 'Cosmic Void', hex: '#0a0714', role: 'Arena Darkness' },
      { label: 'Electric Cyan', hex: '#06b6d4', role: 'Arena Primary' },
      { label: 'Ultra Violet', hex: '#a855f7', role: 'Rank & Tier Accents' },
      { label: 'Hot Amber', hex: '#fbbf24', role: 'Match Countdown' },
    ],
  },
  'paper-lab': {
    id: 'paper-lab',
    name: 'Paper Laboratory (High-Contrast Light / Blueprint)',
    tagline: 'Technical Blueprint & Monolithic Contrast',
    description: 'Crisp, bright technical paper ivory background with deep obsidian ink typography, blueprint grid accents, forest emerald solves, and crisp mechanical cards. Excellent contrast for daytime halls.',
    vibe: 'Academic, Architectural, Blueprint, Crisp',
    bestFor: 'Bright daylight lecture rooms, academic lab computers, faculty review',
    bgClass: 'bg-[#f4f5f8]',
    cardBg: 'bg-white/90',
    borderClass: 'border-slate-300',
    textPrimary: 'text-slate-900',
    textSecondary: 'text-slate-700',
    textMuted: 'text-slate-500',
    accentClass: 'text-emerald-700',
    accentBadge: 'bg-emerald-100 text-emerald-800 border-emerald-300',
    fontDisplay: 'font-mono font-bold',
    swatches: [
      { label: 'Technical Paper', hex: '#f4f5f8', role: 'Canvas Background' },
      { label: 'Dark Ink', hex: '#0f172a', role: 'Primary Typography' },
      { label: 'Forest Green', hex: '#059669', role: 'Solved Points' },
      { label: 'Cobalt Ink', hex: '#2563eb', role: 'Technical Indicators' },
    ],
  },
};
